#pragma config(UART_Usage, UART1, uartUserControl, baudRate57600, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	char temp;
	while(1){
		temp=getChar(UART1);
		if(temp != '') {
			writeDebugStream("%c \n",temp);

		}
	}
}
